// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileInfoTable():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function InsertFileInfo(arg1:string):Promise<string>;

export function LogButtonClick():Promise<void>;
